on:
  workflow_dispatch

jobs:
  build:

    runs-on: Ubuntu-latest

    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
      SIGMA_URL: ${{ secrets.SIGMA_URL }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # Perform Quick Static Analysis Download SIGMA from Artifactory
    - name: SIGMA
      run: |
        wget --user $ARTIFACTORY_USERNAME --password $ARTIFACTORY_PASSWORD $SIGMA_URL
        chmod +x sigma
        ./sigma -V
        ./sigma analyze --format github ./
        
    # Upload SIGMA findings
    - name: Upload SIGMA results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: sigma-results.json

    # Perform Software Composition Analysis
    - name: Software Composition Analysis with Black Duck
      uses: blackducksoftware/github-action@v2
      with:
        version: 7
        args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --blackduck.trust.cert="true" --detect.blackduck.scan.mode=RAPID'
